version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    working_dir: /usr/src/app
    ports:
      - "8080:8080"
    environment:
      - APP_HOST=localhost
      - DB_HOST=postgres
      - DB_NAME=library
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    depends_on:
      - postgres
    command: sh -c "npm start"

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: